src/index.js, src/inner-html.js, test/inner-html.spec.js
Initial implementation of the behavior. Ready for comments.
I implemented it per these instructions from @EisenbergEffect :
```
1. You can go ahead and implement it using the options syntax. Name the behavior inner-html.
2. So, it should be used like this: inner-html="value.bind: some.prop; sanitizer.call: mySanitizationFunction”
3. The sanitizer should be optional. If it isn’t provided it should fallback to a default santizer.
4. The default sanitizer should also be configurable.
5. Hopefully we can also support the short form: inner-html.bind=“some.prop". I’m not sure if that will work with options configured or not. I might need to do a fix for that, but you can get started on the work and I can try to fix that later.
```
This implementation addresses items 1, 2, and 3. I will need …
=> feat(templating-resources): add innerHTML attached behavior

src/global-behavior.js
Enumerate all jQuery methods when a jQuery module is not found to fix case mismatch due to html attributes being returned in lower case. Emit a warning to include it in the global behavior
https://github.com/aurelia/framework/issues/47
Note: you need to add the aurelia-logging dependency in the application config.js
=> fix (templating-resource): case sensitive jquery plugin names

src/repeat.js
This should make the handleSplices-method a lot faster for all use cases I have tested, especially in cases where the array is swapped and where a lot of views are removed and added. 
Let me know if I have missed something or something does not make sense.
On line 186 is a code path to handle `Array.prototype.reverse()` it's probably the fastest way to handle it but not sure if that could be a code path for other use cases than reverse that would not work (not that I have found though).
=> Repeat performance

src/global-behavior.js
fixed incorrect passing of inner error to Error constructor
note: at some point the AggregateError function should be renamed to aggregateError, and all calls updated also.  AggregateError is a function that returns an aggregate error, not a class.  a common mistake associated with the incorrect name is the incorrect use of new when calling the function
=> fix(GlobalBehavior): throw AggregateError

src/repeat.js
Templating was updated to support animations. Where removeAt() method may return a view or a promise. With this commit the repeater will be able to handle both return values. If its a promise the repeater will wait for it to resolve.
Closes #54
@EisenbergEffect / @jdanyow When reviewing this, in particular see if everything looks ok line 228 - 236. And let me know if any questions or changes should be made. 
This is confirmed by @zewa666 and @stoffeastrom to fix their issues.
=> fix(repeat): handle promises returned by view-slot

src/repeat.js
@martingust can you review this?  I'm a little out of my element here.  I was seeing a memory leak due to the repeat's child views never unbinding when the property the repeat was bound to was assigned a new array instance.
Here's an example:
```javascript
export class Foo {
bars = [];  // bind a repeat to this.
constructor() {
setInterval(() => {
this.bars = ['a', 'b', 'c'];  // this should cause the repeat's child views to unbind
}, 0);
}
}
```
=> fix(repeat): unbind children on property change

src/repeat.js, test/repeat.spec.js
Tests are temporary ignored until we get the infrastructure in place to test classes with bindable property initializers. See issue aurelia/binding#90
Fixes #69
=> fix(repeat): remove views when bindning new items

src/repeat.js, test/repeat.spec.js
@EisenbergEffect Can you please review if this looks like expected behavior. When the view gets re-used the only thing that updates is the execution context's "item", one improvement might be to only update that and manually call `unbind` from inside the repeater, oppose the create a new full execution context. Let me know what you think.
@stoffeastrom I have tested this with some basic scenarios but I know you sortable plugin is a little more edge case, if you get any chance to test it out please let me know. I've created a gist with the compiled version of `repeat.js` https://gist.github.com/martingust/44ebf1f795628a229741
=> fix(repeat): preserve lifecycle when re-using views

src/show.js
Fixes aurelia/templating#100
The valueChanged hook isn't called during initial binding when the model value is undefined because it matches the behavior property's intitial value (undefined).  Introducing the bind hook allows us to handle any initial value.
=> fix(show): use bind hook to handle undefined values

src/css-resource.js
Better fixes #105 with virtually no impact on performance.
The solution here is use a combination of RegEx and Code to fix up CSS URLs. Massive reduction in RegEx complexity allows us to get to where we need to be faster :zap:; then just handle the edge cases for quoted URLs. These changes have virtually no impact in loading performance now. :+1: Roughly a **3x** speedup. Here is the performance difference:
=> Much faster CSS fix up matcher

src/aurelia-templating-resources.js, src/update-trigger-binding-behavior.js, test/array-collection-strategy.spec.js, test/number-strategy.spec.js, test/repeat.spec.js, test/update-trigger-binding-behavior.spec.js
The UpdateTriggerBindingBehavior enables overriding the default input events ('change & input) used in two-way bindings to detect changes in the target element.
Fixes #137
=> feat(UpdateTriggerBindingBehavior): add behavior

src/sanitize-html.js, test/sanitize-html.spec.js
There are scenarios in which untrustedMarkup can be undefined (such as when splicing content into an array that is being repeated in a template) and exceptions are thrown. This change ensures a value of undefined returns null just like a value of null does.
=> Return null on undefined untrustedMarkup

src/if.js
When an if is un-bound and subsequently re-bound, it needs to re-bind it's inner view.
Fixes aurelia/binding#223
=> fix(if): rebind view

test/repeat-integration.spec.js
Without the added `.bind` jasmine thinks that the parameter `viewsRequireLifecycle` is the `done` argument, the current version pulled by the package.json dependency issues a warning for this as `describe` functions do not take a `done` parameter.
=> tests won't run after `git clone ... ; npm install ; jspm install ; gulp test`

src/repeat.js
First of all, I am not sure whether this PR is _the_ desired solution to my issue, but at least it would have made things less confusing to me.
I accidentally set a string rather than an array as replacement for an existing bound collection and got the following error: `cannot call method 'getCollectionObserver' of null`. Diving into the stack trace showed me the error was in the method `_observeCollection()`. I had to step trough this package to find out what actually caused this error and found out no repeat strategy could be selected (which makes sense). I am not sure what the desired behavior of Aurelia would be in such a case, but a general JavaScript error seems to be unwanted.
Please let me know if any additional information is required, I do not have the original code at hand …
=> Silently ignore invalid collections

src/abstract-repeater.js, src/array-repeat-strategy.js, src/aurelia-templating-resources.js, src/map-repeat-strategy.js, src/null-repeat-strategy.js, src/number-repeat-strategy.js, src/repeat.js, src/set-repeat-strategy.js
The `AbstractRepeater` is a base class for all attributes or elements that repeat views/templates over a collection. It's meant primarily to provide an abstraction for anyone who wants to create something like the baked in `repeat` attribute. The flexibility of the interface allows you to implement repeat-esque elements over more complicated components (particularly multi-dimensional datasets like a grid, where each "item"/"row" might actually have multiple views).
I think this is a good place to start, there are a number of nitpicks I can point out off the top of my head:
* `addView` is more like `createAndAddView`
* `insertView` => `insertViewAt`, as well as the above comment
* `removeView` => `removeViewAt`
the list could go on
I'm not sure what kind of conventions y'all prefer, and am …
=> introduce AbstractRepeater

src/css-resource.js
See #189. Throws an error on missing CSS files -- both when bundled and unbundled.
=> fix(css): throw on missing CSS file

src/array-repeat-strategy.js, src/if.js, test/if.spec.js
Changes are now being queued when animating, same approach as `repeat`.
@jdanyow @EisenbergEffect If this looks to you guys, this is ready to be merged.
=> fix(if): queue up changes when animating

src/aurelia-templating-resources.js
AbstractRepeater isn't very useful if you don't have access to the repeat strategies! I stupidly left this out of my AbstractRepeater PR it seems..
=> fix(exports): export RepeatStrategyLocator

src/aurelia-templating-resources.js
As I'm not sure if [this syntax](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/2ffd03520231a63f964df9564e556fd9867989e8#diff-1fdf421c05c1140f6d71444ea2b27638R3) is supported by all loaders I'd rather follow the standard and export the things I need from index.js
=> refactor(index): export repeat strategies

src/aurelia-templating-resources.js
These functions are needed by `UI-Virtualization` and needs to be released before `UI-Virtualization`.
=> refactor(index): export helper functions

src/aurelia-templating-resources.js
LESS and SASS extensions can now be loaded as `<style>` by `<require from=style.less>` in views.
Of course, content should previously have been properly compiled to CSS.
Fixed #277
=> feat(templating): support popular transpilers

src/if.js
This PR introduces an `else` custom attribute that can be used directly following a `if` binding:
```html
<div if.bind="whatever">Whatever is truthy!</div>
<div else>No luck</div>
```
It also introduces an option to `if`.
- `condition` is the default option, as above.
- `swap: "after"|"with"|"before"` coordinates the animations (if any) between the `if` and the `else` templates.
```html
<div if="condition.bind: whatever; swap: with">Yes</div>
<div else class="au-animate">No</div>
```
The advantages of this are:
- Simpler, more intuitive to use. Especially when `condition` is a complex expression.
- The pair only subscribes for changes once.
- Coordinated animations.
⚠️ **Don't merge this before aurelia/templating#537 and remember to bump the minimum dependency!!** Otherwise using `if` …
=> feat(templating): else custom attribute

src/map-repeat-strategy.js, test/map-repeat-strategy.spec.js, test/mocks.js
Fix propsed for wrong map indexes after map content changed. See #287 .
I also added some tests for map-repeat-strategy. 
The 'should correctly handle adding items after clear (issue 287)' test is somehow always ok. Even without the fix. I think this has something to do with wrong override context being bound to the viewSlot.children. But this is just an error in the test which I dont understand. When I step through map-repeat-strategy.js and updateOverrideContext() in repeat-utilities.js the index is now being set right! 
@jdanyow Hope that helps :)
=> proposed fix for issue 287

test/repeat-integration.spec.js
When I write test for my aurelia plugin [bcx-aurelia-reorderable-repeat](https://github.com/buttonwoodcx/bcx-aurelia-reorderable-repeat), I discovered the `createAssertionQueue` function I copied from [aurelia-ui-virtualization](https://github.com/aurelia/ui-virtualization) (it copied from this repo I guess) has bug.
I believe the intended behaviour for
```javascript
let nq = createAssertionQueue();
ng(work0); ng(work1); ng(work2);
```
is to run 3 works in serial, everyone is in different JavaScript runloop.
```
start -> work0() -> work1() -> work2()
```
But the existing implementation got it wrong. All 3 works runs in the same next JavaScript runloop;
```
start -> work0()
start -> work1()
start -> work2()
```
To demonstrate this issue, run following code in node. It uses 1 second delay …
=> test: fix createAssertionQueue behaviour in repeat-integration spec.

src/focus.js
This PR replaces 2 arrow functions: `focusListener` & `blurListener` by `handleEvent`, leveraging event target interface for lower memory consumption.
=> refactor(Focus): Use handleEvent instead of arrow functions

src/aurelia-templating-resources.js, src/else.js, src/if-core.js, src/if.js
fixes https://github.com/aurelia/templating-resources/issues/312
Basically, we want to export custom elements and attributes in individual files. So I've moved `else` out of `if` and registered it in `aurelia-templating-resources.js`
built version is in branch: https://github.com/JeroenVinke/templating-resources/tree/else-own-file-built
=> fix(if): resolve if.html error

src/else.js, src/if.js, test/else.spec.js
Issue: #322 
This PR fixes the issue that an else block is rendered without a bindingContext in case that the condition is falsy and the view is rendered initially.
I also added some simple unit tests to check if the correct block is rendered and the swapping logic works properly.
=> fix(if-else): Fixed missing binding context when rendering else block

src/analyze-view-factory.js
The 'else' attribute was added to aurelia-templating-resources 1.5.0, but seems like it was left out from the 'livecycleOptionBehaviors'. This leads to unnecessary work when removing av view from the DOM that uses the 'else' attribute.
=> Added 'else' to lifecycleOptionalBehaviors in analyze-view-factory

config.js, src/debounce-binding-behavior.js, src/update-trigger-binding-behavior.js, test/debounce-binding-behavior.spec.js
I tried to fix the throttle but pretty much gave up on the test. I think we should fix debounce first, regardless throttle status.
resolves #319
fixes aurelia/binding#625
fixes aurelia/binding#485
The gist of throttle working is here https://gist.run/?id=4fec87bd40bdfbd7ed10e7ad8f37fdd8 But I couldn't apply jasmin clock against it.
@jdanyow
=> fix(debounce): debounce binding call instead updatesource

src/update-trigger-binding-behavior.js, test/update-trigger-binding-behavior.spec.js
- Ensure we dispose the listener before resetting the handler back to its original version.
- Use `EventSubscriber`
@EisenbergEffect this requires `aurelia-binding@1.7.x` and the fix at aurelia/binding#674
=> fix(UpdateTrigger): sync with binding

src/repeat.js, test/repeat-integration.spec.js
This PR is for https://github.com/aurelia/framework/issues/830
I tried to reproduce the broken behavior in test but failed.
@EisenbergEffect @jdanyow
=> fix(Repeat): ignore mutation while processing instance changed

src/if-core.js, src/if.js, test/if.spec.js
fix #320 
I believe the syntax of this `if` is:
```html
if="condition.bind: someValue; cache: false"
```
Don't know if the CI fail is due to my changes. All seems good locally.
=> Ability to turn of caching of view instance when using if

src/signal-binding-behavior.js
Specify "names" parameter explicitly in `SignalBindingBehavior.bind` to improve the typescript typings.
Closes #338
=> fix: improve typescript typings of SignalBindingBehavior.bind

src/repeat-utilities.ts
Thanks to @veyselozdemir for discovering this.
Explicitly type `createOverrideContext` to support lower version of TS
@EisenbergEffect 
close #375
=> fix(typings): explicit return typings for createFullOverrideContext

src/array-repeat-strategy.ts, src/aurelia-templating-resources.ts, src/interfaces.ts, src/repeat.ts, test/map-repeat-strategy.spec.ts, test/mocks.ts, test/number-repeat-strategy.spec.ts, test/repeat.issue-378.spec.ts, test/repeat.spec.ts, test/sanitize-html.spec.ts, test/test-interfaces.ts, test/test-utilities.ts
At the moment, it simply walks through the instruction list to get the right matcher binding, which will break in scenario where folks have bindings with matcher in it, for example: a list of input box:
```html
<label repeat.for="item of items">
<input matcher.bind="itemMatcher" />
</label>
```
Current code will mis-identify `matcher.bind="itemMatcher"` as repeat matcher.
Fixes #378 
need to investigate #295
---
Explanation:
Every repeat by default looks for a `matcher` binding by walking through view factory instructions and looking for a binding expression targeting a property with name `matcher`. What our current implementation does not do is distinguishing between a `matcher` binding expression on the repeated element, and any element inside it. So for the following template:
```html …
```
=> fix(repeat): properly extract matcher binding

package-lock.json, src/compose.ts, test/compose.integration.spec.ts, test/compose.spec.ts
This PR introduces bindable activation-strategy for compose. The default strategy is 'invoke-lifecycle', which is also the current strategy. The strategy 'replace' forces re-creation of bound view and view-model on model change.
Fixes #381
=> feat(compose): bindable activation-strategy
