src/show.js

Instead of adding the aurelia-hide style tag to the body, add it to the head so it is evaluated properly

fix(show): append aurelia-hide style to head

---

src/repeat.js

This one I have iterated over a few times along the way as understood more how its working. The last I came up with was to just handle the change records for maps, switch over record.type and add/remove views accordingly. 
One difference from array is that we don't have the index, only key. Right now I'm iterating over viewSlot children to see where keys match to get the index. We might wanna come up with a better way to handle this.
The testing I have done it seems to work, but I'm probably missing something. Let me know if you see any issues/improvements to this solution and ill make necessary changes.

feat(repeat): implement support for map

---

src/repeat.js

Depends on: https://github.com/aurelia/templating-binding/pull/11

Don't allocate unnecessay arrays and refactoring

---

src/index.js
src/with.js

This binding should be similar to other libs where it sets context of an element

feat(with): Add WIP with binding

---

src/repeat.js

BUG=https://github.com/aurelia/templating-resources/issues/27

init 'context.$parent' when create base execution context.

---

src/repeat.js

fix(repeat): null/undefined should not cause error

---

src/repeat.js

fix(repeat): add value as bindable

---

src/global-behavior.js

fix(GlobalBehavior): improve handler-not-found message

---

src/repeat.js

feat(repeat): add support for iterating numbers

---

src/if.js

I think there is typo in the `if`. It should be `isBound` not `bound` https://github.com/aurelia/templating/blob/master/src/view.js#L14

Typo in the "if"

---

src/if.js

Closes #56 
This bug is blocking me, so I made a PR. Can you review it?

fix(if): fix passing context binding to the view factory

---

karma.conf.js
src/repeat.js
test/repeat.spec.js

When discussing the implementation of iterating numbers we said to not handle changes, for some reason I can't remember. It was relatively easy to handle so I created this PR. Let me know if you see any reasons to not do this. 
Closes #81

fix(repeat): handle changes for numbers

---

src/if.js
test/if.spec.js
test/repeat.spec.js

And adding and fixing tests for `repeat` and `if`.

fix(if): delay call to unbind via micro task

---

package.json
src/repeat.js
test/if.spec.js
test/repeat.spec.js

fix(repeat): update binding context after animations have finished

---

src/repeat.js
test/repeat.spec.js

@EisenbergEffect Please take a look if this implementation of view caching in the repeater looks alright.

Repeat view caching implementation

---

src/repeat.js

fix(repeat): create full bindingContext before inserting view

---

src/array-collection-strategy.js
src/collection-strategy-locator.js
src/collection-strategy.js
src/map-collection-strategy.js
src/number-strategy.js
src/repeat.js
test/array-collection-strategy.spec.js
test/mocks.js
test/number-strategy.spec.js
test/repeat.spec.js

@EisenbergEffect This is work in progress to (possible) get @jdanyow started doing his work and for you to review. The implementation should be pretty ready, but needs more testing, might want to break the strategy classes out to different files. Unit tests need more work and probably not green atm.

Repeat strategy pattern

---

src/repeat.js
test/array-collection-strategy.spec.js
test/mocks.js
test/number-strategy.spec.js
test/repeat.spec.js

feat(repeat): observe inner expression

---

package.json
test/repeat-integration.spec.js

This is ready to merge if it looks good.

test(repeat): integration tests

---

src/update-trigger-binding-behavior.js

Related to aurelia/binding#253

refactor(updateTrigger): sync with binding API changes

---

src/array-repeat-strategy.js
test/array-repeat-strategy.spec.js
test/repeat-integration.spec.js

This is an in process PR for fixing #167 
It currently just includes a test that demonstrates the issue.

fix updates during leave animation

---

src/repeat-strategy-locator.js
src/set-repeat-strategy.js
test/repeat-integration.spec.js

@EisenbergEffect @jdanyow If looks good this can be merged. [set-observation PR](https://github.com/aurelia/binding/pull/277) is required for this PR.

feat(repeat): add strategy for repeating over Set objects

---

src/hide.js
test/hide.spec.js
test/show.spec.js

I would like to have a hide binding as already discussed here in #177 
While at it I also added tests for the show binding

Added hide binding and tests for show.

---

src/array-repeat-strategy.js

I had no idea array.slice can be used to clone an Array, so the comments should help others reading the code.

style(array-repeat-strategy): add comments about array.slice usage

---

src/abstract-repeater.js
src/array-repeat-strategy.js
src/repeat-utilities.js
src/repeat.js
test/repeat-integration.spec.js

Fixes https://github.com/aurelia/templating-resources/issues/213.
Blocked on: https://github.com/aurelia/templating/pull/324.
Demo: https://gist.run/?id=af08bd464f72a809d07639b2d9f88a38

perf(repeat): intelligently reuse items from previous instance

---

src/repeat-utilities.js

Fix for the bug spotted by @CasiOo [here](https://github.com/aurelia/templating-resources/commit/5ad659b852931da26c79d2b204fc0424aebb37bd#commitcomment-17229019).

fix(repeat-utilities): remove unnecessary variable and loop evaluation

---

src/aurelia-hide-style.js
src/aurelia-templating-resources.js
src/hide.js
src/show.js
test/hide.spec.js
test/show.spec.js

fix(aurelia-hide): remove /deep/ combinator

---

config.js
package.json
test/array-repeat-strategy.spec.js
test/number-repeat-strategy.spec.js
test/repeat.spec.js

@EisenbergEffect This requires `testing` to be released with [this](https://github.com/aurelia/testing/pull/14).
@jdanyow There are two tests failing I couldn't get to pass, [this](https://github.com/aurelia/templating-resources/blob/master/test/hide.spec.js#L36) for `hide` and [this](https://github.com/aurelia/templating-resources/blob/master/test/show.spec.js#L36) for `show`. Looks like same issue, both giving me `Expecting undefined to be true`. Any ideas?

test(repeat): use the component tester

---

test/debounce-binding-behavior.spec.js
test/throttle-binding-behavior.spec.js

test(bounding, throttle): Support catpuring event

---

src/aurelia-templating-resources.js

Add PLATFORM.moduleName() inside .globalResources().
See aurelia/pal#21

chore(build): document dynamic dependencies

---

src/set-repeat-strategy.js
test/mocks.js
test/set-repeat-strategy.spec.js

Adds a couple of tests for SetRepeatStrategy, adds failing test for #284 and proposes a fix

fix negative index in SetRepeatStrategy

---

src/repeat.js

closes https://github.com/aurelia/animator-velocity/issues/21 and
https://github.com/aurelia/templating-resources/issues/298

fix(repeat): bug when "if.bind", "repeat.for" and animations are used in a certain way

---

src/css-resource.js

fix(css-resource): ensure only global styles get injected globally

---

src/compose.js
test/compose.spec.js

Await async tasks to complete before processing changes fix #299, fix #240
* accumulate all changes
* let all change handlers run before processing the changes
* do not process any changes if there is a pending composition/activation
* `compostionEngine.compose()` has not finished
* `currentViewModel.activate(model)` has not finished
* after a composition/activation has completed process any changes

fix(compose): await composition/activation

---

src/binding-signaler.js
src/signal-binding-behavior.js

This PR follows & requires the new feature of value converter trigger in aurelia/binding#626

refactor(Signal): use new signal mechanism

---

src/else.js
src/if-core.js
src/if.js
test/else.spec.js
test/if-test.js
test/if.spec.js
test/repeat.spec.js

fixes #328, #327, #326, #322, #317, #315

fix(if): nested ifs don't work properly

---

.circleci/config.yml
config.js
karma.conf.js
package-lock.json
package.json

fix(ci): update deps, jspm deps, test deps, ci

---

src/html-sanitizer.js

with regards to https://discourse.aurelia.io/t/vulnerability-disclosure-contact/2390

chore(html-sanitizer): add an explicit security warning to the constructor of htmlsanitizer

---

src/repeat.ts

closes #390 
cc @AquilaSands @EisenbergEffect

fix(repeat): use utility fns for ie11 compat

---

src/repeat.ts
test/repeat.issue-295.spec.ts

Thanks to @Seebiscuit for the ping at https://github.com/aurelia/templating-resources/issues/295
cc @EisenbergEffect @fkleuver

fix(repeat): extract matcher once
